version: '2.1'
services:

  fullfeedrss:
    build: .
    image: "fivefilters-full-text-rss-docker:3.5"
    volumes:
      - rss-cache:/var/www/html/cache"
    expose:
      - "80"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
volumes:
  rss-cache:
