name: Docker build and push

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docker-compose.yml'
  schedule:
    - cron: '0 13 * * 0'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        run: |
          docker buildx build --push \
            --tag heussd/fivefilters-full-text-rss:latest \
            --platform  linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 .
